const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const code=fs.readFileSync(require('path').join(__dirname,'index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({TextEncoder,console});
vm.runInContext(code.split('// ── UI RENDERING')[0]+'\nglobalThis.api={Campfires,State,Import,PlanStore,PlanSession};',ctx);
const {Campfires:C,State:S,Import:I,PlanStore:P,PlanSession:U}=ctx.api;
I.loadRoster({gameVersion:'forever',raid:'forever10',players:['Miner','Fisher','Engineer','MinerTwo'].map(name=>({name,class:'MAGE',spec:'Frost',role:'caster_dps',groupNumber:1}))});
S.planId='camp-test';
S.campfires={professions:[{player:'Miner',profession:'Mining',skill:20},{player:'MinerTwo',profession:'Mining',skill:300},{player:'Fisher',profession:'Fishing',skill:300},{player:'Engineer',profession:'Engineering',skill:300}],fires:[{name:'Buffs',capacity:3,assets:[]},{name:'Services',capacity:5,assets:[]}]};
assert(!C.assign(0,{player:'Miner',asset:279948}),'skill gating');
assert(C.assign(0,{player:'Miner',asset:279960}));
assert(!C.assign(1,{player:'Miner',asset:279960}),'one asset across all fires');
assert(!C.assign(0,{player:'MinerTwo',asset:279952}),'duplicate buff family');
assert(C.assign(0,{player:'Fisher',asset:279966}));
assert(C.assign(0,{player:'Engineer',asset:279949}));
assert.equal(C.eligible(0).length,0,'capacity enforced');
const expected=JSON.stringify(S.campfires);
const share=I.exportShareString();
assert(I.importAddonString(share).success);
assert.equal(JSON.stringify(S.campfires),expected,'share retains profession and assignments');
assert(I.loadRoster(JSON.parse(JSON.stringify(I.exportRoster()))));
assert.equal(JSON.stringify(S.campfires),expected,'JSON retains campfires');
S.planId='camp-test';const snap=P.capture();S.campfires=C.empty();assert(P.restore(snap));
assert.equal(JSON.stringify(S.campfires),expected,'working plan restore');
U.ready=true;U.previous=null;U.observe();S.campfires.fires[0].name='Changed';U.observe();assert(U.undoLast());
assert.equal(S.campfires.fires[0].name,'Buffs','undo restores campfires');
S.campfires.professions[0].skill=1;S.campfires=C.clean(S.campfires);
assert(!S.campfires.fires[0].assets.some(a=>a.player==='Miner'),'skill reduction removes ineligible assignment');
S.roster=S.roster.filter(p=>p.name!=='Fisher');S.campfires=C.clean(S.campfires);
assert(!S.campfires.fires[0].assets.some(a=>a.player==='Fisher'),'removed members cannot contribute');
assert.equal(C.clean({fires:[{capacity:99,assets:[]}]}).fires.length,0);
assert.equal(C.clean({professions:[null],fires:[null,{capacity:3,assets:[null]}]}).fires[0].assets.length,0);
I.loadRoster({raid:'bt',players:[]});assert.equal(S.campfires.fires.length,0,'legacy loads clear campfires');
assert.equal(C.catalog.length,34);
console.log('Campfire tests passed: eligibility, capacity, duplicates, contributor uniqueness, saves, shares, undo and cleanup.');
